apiVersion: v1
kind: Service
metadata:
  name: sample-node-service
  namespace: default
spec:
  selector:
    app: sample-node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
